_extends: org-settings

repository:
  name: reference-architecture
  description: TELUS Reference Architecture Documentation
  topics: architecture, documentation, standards
  homepage: https://telus.com/digital
  private: false
  has_issues: false

labels:
  - name: security
    description: Security related topic
    color: EE3F46

  - name: chore
    description: Changes that don't modify core files
    color: FEF2C0

  - name: enhancement
    description: New feature or request
    color: 5EBEFF

  - name: optimization
    description: Performance or Code Optimization
    color: 5EBEFF

  - name: feature
    description: New Feature
    color: 91CA55

  - name: in progress
    description: Currently being worked on
    color: FBCA04

  - name: invalid
    description: Something doesn't seem right
    color: D2DAE1

  - name: wontfix
    description: This will not be worked on
    color: D2DAE1

  - name: duplicate
    description: This issue or pull request already exists
    color: D2DAE1

  - name: on hold
    description: No work planned on this for now
    color: D2DAE1

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        dismissal_restrictions:
          teams:
            - architecture-support

      required_status_checks:
        strict: true
        contexts:
          - 'Validate'

      restrictions:
        teams:
          - architecture-support
